import Head from 'next/head'
import Header from '../components/Header';
import styles from '../styles/Home.module.css';
import Feed from '../components/Feed'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Instagram 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/*Header*/}
      <Header />

      {/*Feed*/}
      <Feed />

      {/*Modal*/}
    </div>
  )
}
